#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.kktt.jesus.pojo
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


---

#开发配置
spring:
  profiles: dev

  datasource:
    test1:
      url: jdbc:mysql://47.99.236.189:3307/enjoy?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
    test2:
      url: jdbc:mysql://47.99.236.189:3307/relax?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource


#server:
#  port: 443
#  ssl:
#    key-store: classpath:jjflyo.com.pfx
#    key-store-password: i0n1rea42857
#    keyStoreType: PKCS12

